#!/bin/bash
function deactivate() {
	if [ -n ${GOVENV_OLD_PATH} ]; then
		PATH=${GOVENV_OLD_PATH}
		export PATH
		unset GOVENV_OLD_PATH
	fi

	if [ -n ${GOVENV_OLD_PS1} ]; then
		PS1=${GOVENV_OLD_PS1}
		export PS1
		unset GOVENV_OLD_PS1
	fi

	if [ -n ${GOROOT} ]; then
		unset GOROOT
	fi

	if [ -n ${GOPATH} ]; then
		unset GOPATH
	fi

	unset GOVENV_PROJECT
	unset GOVENV_ENABLE
}

# Activation
if [ -z "${GOVENV_ENABLE+x}" ]; then
	GOVENV_OLD_PATH=${PATH}
	GOVENV_OLD_PS1=${PS1}

	GOROOT=/Users/yoshimura/Desktop/goenv/src/github.com/necomeshi/govirtualenv/script
	GOPATH=/Users/yoshimura/Desktop/goenv/src/github.com/necomeshi/govirtualenv/script
	GOVENV_PROJECT=project

	PATH=${GOROOT}/bin:${PATH}
	PS1="(${GOVENV_PROJECT}) ${PS1}"

	export PS1 PATH GOROOT GOPATH GOVENV_ENABLE=1 GOVENV_PROJECT
else
	echo "Already in the project. First do 'deactivate'"
fi
